package com.moretv.bi.global

/**
  * Created by Will on 12/13/2016.
  */
object LogTypes {

  val ACTION = "action"
  val APPACCESS = "appaccess"
  val BACK = "back"
  val BUTTON = "button"
  val BUTTONCLICK = "buttonclick"
  val CLICKSEARCHRESULT = "clickSearchResult"
  val COLLECT = "collect"
  val DELETECOLLECT = "deletecollect"
  val DETAIL = "detail"
  val EDITENTRANCE = "editentrance"
  val ENTER = "enter"
  val ENTRANCEVIEW = "entranceview"
  val EVALUATE = "evaluate"
  val EXIT = "exit"
  val FOCUS = "focus"
  val HOMEACCESS = "homeaccess"
  val HOMEVIEW = "homeview"
  val INPUTMETHODUSAGE = "inputmethodusage"
  val INTERVIEW = "interview"
  val KEY = "key"
  val KEYEVENT = "keyEvent"
  val KEYEVENT_KEY = "keyEvent_KEY"
  val KEYEVENT_MENU = "keyEvent_MENU"
  val LIVE = "live"
  val LIVEBUTTON = "livebutton"
  val LIVECENTERVIEW = "livecenterview"
  val LOGIN_PROCESS = "login-process"
  val MATCHDETAIL = "matchdetail"
  val MEDUSA_MV_CLICKRESULT = "medusa-mv-clickResult"
  val MEDUSA_MV_STATION_CLICKRESULT = "medusa-mv_station-clickResult"
  val MENU = "menu"
  val MTVACCOUNT = "mtvaccount"
  val PAGEVIEW = "pageview"
  val PLAY = "play"
  val PLAY_PAUSE = "play-pause"
  val PLAY_PAUSEMERGER = "play-pauseMerger"
  val PLAYQOS = "playqos"
  val PLAYVIEW = "playview"
  val POSITIONACCESS = "positionaccess"
  val SEARCH_TABVIEW = "search-tabview"
  val SEARCHENTRANCE = "searchEntrance"
  val SELECTACCOUNT = "selectaccount"
  val SPORTSLIVEDETAIL = "sportslivedetail"
  val SPORTSSUBSCRIBE = "sportssubscribe"
  val STARTPAGE = "startpage"
  val SUBJECT = "subject"
  val SUBSCRIBE = "subscribe"
  val SWITCHINPUTMETHOD = "switchinputmethod"
  val SWITCHONOFF = "switchonoff"
  val TABVIEW = "tabview"
  val VIDEOBUTTON = "videobutton"
  val SET = "set"
  val MORETV_MTV_ACCOUNT = "moretv_mtv_account"
  val LOGINLOG = "loginlog"
}
