package com.moretv.bi.util

/**
  * Created by Will on 2016/8/3.
  * 白名单和黑名单工具类，存放渠道号的白名单和黑名单
  */
object PromotionChannelListUtil {

  val regex = "^[\\w\\-]+$".r

  def transform(pc:String) = {
    if(pc == null) "null" else if(pc == "") "kong" else pc
  }

  def isBlack(pc:String) = {
    if(pc != null) {
      if(pc == "") false
      else {
        regex findFirstIn pc match {
          case Some(m) => !whiteList.contains(pc) && blackList.contains(pc)
          case None => true
        }

      }
    } else false
  }

  def isWhite(pc:String) = !isBlack(pc)

  private val blackList = List("88888e888",
    "musicgeneral6633x3X6",
    "dangbei6633x3X6",
    "dangbeie888",
    "5476",
    "ei",
    "888881",
    "dangbei1",
    "xunmae888",
    "inphic6633x3X6",
    "zhengduoy",
    "dan",
    "guan",
    "xunma6633x3X6",
    "101280501",
    "kaibo",
    "generale888",
    "shcfah7",
    "general6633x3X6",
    "musicgenerale888",
    "dang",
    "dir",
    "f7postore",
    "huansto",
    "musicgeneral1",
    "inphice888",
    "aaq",
    "888886633x3X6",
    "aijia",
    "moretvTestVer",
    "general1",
    "88888",
    "xia",
    "shaga",
    "corrupt",
    "changhongshequ",
    "phpinfo",
    "dangbe")

  private val whiteList = List("null",
    "qcast",
    "yztwl",
    "mohexianxia",
    "10moons",
    "alilianmeng",
    "chenxin",
    "chuangshiwei",
    "chuangweixianxia",
    "diyomate",
    "easitek",
    "egreat",
    "feikan",
    "gongjin",
    "haier",
    "haixinxianxia",
    "haotao",
    "himedia",
    "hisense",
    "hongyue",
    "huan",
    "huanstore",
    "huanwang",
    "inphic",
    "jingbaohui",
    "kaiboer",
    "kaiboerupdate",
    "konka",
    "lianmenghezi",
    "meiruhua",
    "meizi",
    "mele",
    "mibox3",
    "musicdamai",
    "musickaiboer",
    "musickonka",
    "rockchip",
    "tcl",
    "tena",
    "tianmao",
    "tianmaomarket",
    "tongshuai",
    "waixingkeji",
    "xunma",
    "yunbo",
    "yunos",
    "zekaisi",
    "guanwang",
    "dianshijia",
    "dianshijialiulanqi",
    "hdp",
    "HDPlive",
    "leshiliulanqi",
    "letvbrowser",
    "qsptv",
    "xiaoying",
    "xiaoyinggongju",
    "zhengduoyan",
    "BYT",
    "360forum",
    "7poforum",
    "aijiaforum",
    "baidu",
    "baiduopenapi",
    "baiduyingbang",
    "baiduyun",
    "baiduyunforum",
    "channel_value",
    "damaitieba",
    "dianshijiaforum",
    "dianshimaoba",
    "forum",
    "forum_q",
    "general",
    "HDPforum",
    "inphicforum",
    "kukaiforum",
    "letvforum",
    "letvstore",
    "letvyun",
    "moretvprice",
    "musicgeneral",
    "MZ6",
    "otherforum",
    "PC6",
    "pchome",
    "shafaforum",
    "tanghao",
    "tianmaotieba",
    "tianshang",
    "tieba",
    "ucliulanqi",
    "weibo",
    "wqqqun",
    "xiaomiforum",
    "xiaomimarket",
    "xiaomitieba",
    "XTTD",
    "yonghutuiguang",
    "yunosforum",
    "zhineng8",
    "zhuoqi",
    "zndsforum",
    "ZSL",
    "空白",
    "chenjian",
    "jiahu",
    "jinlewei",
    "leshishuaji",
    "shengshi",
    "shichuangshuma",
    "360dianshizhushou",
    "7postore",
    "aijiatv",
    "dangbei",
    "music360",
    "musicdangbei",
    "shafa",
    "xiaobai",
    "shafah1",
    "shafah2",
    "quanjiahe",
    "hanrong",
    "guowangtong",
    "fangguo",
    "changhong",
    "boshilian",
    "7postoreh2",
    "7postoreh1",
    "ZIDOO",
    "yidian",
    "yibo",
    "shafah3",
    "philips",
    "zivoo",
    "UT",
    "meinatu",
    "dangbeih1",
    "chuangweihezi",
    "zivoo",
    "jiali",
    "duolestore",
    "shafah4",
    "shafah5",
    "shafah6",
    "shafah7",
    "shafah8",
    "shafah9",
    "shafah10",
    "shafah11",
    "xiazaizhan",
    "xiangkanzhushou",
    "dangbeih2",
    "dianshijiazhibo",
    "judou",
    "aliyingshi",
    "fengying",
    "MoreTV_TVApp2",
    "quanqiubo",
    "shafah11",
    "shafah12",
    "shafah13",
    "shafah14",
    "shafah15",
    "tb",
    "tc",
    "weipao",
    "update",
    "wuxing",
    "DSZJforum",
    "changhongforum",
    "shafah6 ",
    "shafah7   ",
    "anzhi",
    "zhuoying",
    "nibiru",
    "dangbeih3",
    "JWD",
    "beva",
    "tmmhtieba")


}
