type=command
dependencies=medusa_moretv_isExist
path=/log/medusaAndMoretvMerger/[key_day]/[realLogType]
mainclass=com.moretv.bi.report.medusa.medusaAndMoretvParquetMerger.CollectLogMerger
command=sh ${working.dir}/../../bin/submit.sh ${mainclass} --startDate ${startDate} --numOfDays ${numOfDays} --alarmFlag ${alarmFlag} --deleteOld ${deleteOld}
command.1=sh ${working.dir}/../../bin/metadataManage.sh --realLogType collect --username dw --password dw@whaley --path ${path} --dbName ${dbName} --tabPrefix ${tabPrefix} --productCode ${productCode} --appCode ${appCode} --startDate ${startDate} --endDate ${endDate} --offset ${offset} --step ${step} --deleteOld ${deleteOld}
