type=command
dependencies=medusa_moretv_isExist
path=/log/medusa/parquet/[key_day]/[realLogType]
mainclass=com.moretv.bi.dbOperation.db.PlayQosToParquet
command=sh ${working.dir}/../../bin/submit.sh ${mainclass} --startDate ${startDate} --numOfDays ${numOfDays} --alarmFlag ${alarmFlag} --deleteOld ${deleteOld}
command.1=sh ${working.dir}/../../bin/metadataManage.sh --realLogType playqos_flatten --username dw --password dw@whaley --path ${path} --dbName ${dbName} --tabPrefix ${tabPrefix} --productCode ${productCode} --appCode main3x --startDate ${startDate} --endDate ${endDate} --offset ${offset} --step ${step} --deleteOld ${deleteOld}
